openapi: '3.0.2'
info:
  title: Entschuldigungssystem
  version: '1.0'
servers:
  - url: todo
paths:
  /students:
    $ref: ./students.yml#/paths/~1students
  /admin:
    $ref: ./admin.yml#/paths/~1admins
  /admin/{adminId}:
    $ref: ./admin.yml#/paths/~1admins~1{adminId}
